#[allow(dead_code)]
pub struct CaptureEntry {
    pub family: &'static str,
    pub component: &'static str,
    pub variant: Option<&'static str>,
    pub state: &'static str,
    pub script: Option<&'static str>,
    pub labels: &'static [&'static str],
    pub filename: &'static str,
    pub is_website_card: bool,
    pub is_regression: bool,
}

pub static MANIFEST: &[CaptureEntry] = &[
    // --- 33 family default showcases ---
    CaptureEntry {
        family: "alert",
        component: "alert",
        variant: None,
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-alert.png",
        is_website_card: true,
        is_regression: false,
    },
    CaptureEntry {
        family: "avatar",
        component: "avatar",
        variant: None,
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-avatar.png",
        is_website_card: true,
        is_regression: false,
    },
    CaptureEntry {
        family: "badge",
        component: "badge",
        variant: None,
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-badge.png",
        is_website_card: true,
        is_regression: false,
    },
    CaptureEntry {
        family: "button",
        component: "button",
        variant: None,
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-button.png",
        is_website_card: true,
        is_regression: false,
    },
    CaptureEntry {
        family: "canvas",
        component: "canvas",
        variant: None,
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-canvas.png",
        is_website_card: true,
        is_regression: false,
    },
    CaptureEntry {
        family: "card",
        component: "card",
        variant: None,
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-card.png",
        is_website_card: true,
        is_regression: false,
    },
    CaptureEntry {
        family: "checkbox",
        component: "checkbox",
        variant: None,
        state: "default",
        script: None,
        labels: &["checkbox"],
        filename: "akar-checkbox.png",
        is_website_card: true,
        is_regression: false,
    },
    CaptureEntry {
        family: "container",
        component: "container",
        variant: None,
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-container.png",
        is_website_card: true,
        is_regression: false,
    },
    CaptureEntry {
        family: "data_item",
        component: "data_item",
        variant: None,
        state: "default",
        script: None,
        labels: &["data_item"],
        filename: "akar-data-item.png",
        is_website_card: true,
        is_regression: false,
    },
    CaptureEntry {
        family: "data_list",
        component: "data_list",
        variant: None,
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-data-list.png",
        is_website_card: true,
        is_regression: false,
    },
    CaptureEntry {
        family: "drawer",
        component: "drawer",
        variant: None,
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-drawer.png",
        is_website_card: true,
        is_regression: false,
    },
    CaptureEntry {
        family: "dropdown",
        component: "dropdown",
        variant: None,
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-dropdown.png",
        is_website_card: true,
        is_regression: false,
    },
    CaptureEntry {
        family: "heading",
        component: "heading",
        variant: None,
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-heading.png",
        is_website_card: true,
        is_regression: false,
    },
    CaptureEntry {
        family: "label",
        component: "label",
        variant: None,
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-label.png",
        is_website_card: true,
        is_regression: false,
    },
    CaptureEntry {
        family: "link",
        component: "link",
        variant: None,
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-link.png",
        is_website_card: true,
        is_regression: false,
    },
    CaptureEntry {
        family: "modal",
        component: "modal",
        variant: None,
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-modal.png",
        is_website_card: true,
        is_regression: false,
    },
    CaptureEntry {
        family: "navbar",
        component: "navbar",
        variant: None,
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-navbar.png",
        is_website_card: true,
        is_regression: true,
    },
    CaptureEntry {
        family: "paragraph",
        component: "paragraph",
        variant: None,
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-paragraph.png",
        is_website_card: true,
        is_regression: false,
    },
    CaptureEntry {
        family: "progress",
        component: "progress",
        variant: None,
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-progress.png",
        is_website_card: true,
        is_regression: false,
    },
    CaptureEntry {
        family: "radio",
        component: "radio",
        variant: None,
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-radio.png",
        is_website_card: true,
        is_regression: false,
    },
    CaptureEntry {
        family: "scroll_area",
        component: "scroll_area",
        variant: None,
        state: "default",
        script: None,
        labels: &["scroll_area"],
        filename: "akar-scroll-area.png",
        is_website_card: true,
        is_regression: false,
    },
    CaptureEntry {
        family: "select",
        component: "select",
        variant: None,
        state: "default",
        script: None,
        labels: &["select"],
        filename: "akar-select.png",
        is_website_card: true,
        is_regression: false,
    },
    CaptureEntry {
        family: "separator",
        component: "separator",
        variant: None,
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-separator.png",
        is_website_card: true,
        is_regression: false,
    },
    CaptureEntry {
        family: "skeleton",
        component: "skeleton",
        variant: None,
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-skeleton.png",
        is_website_card: true,
        is_regression: false,
    },
    CaptureEntry {
        family: "slider",
        component: "slider",
        variant: None,
        state: "default",
        script: None,
        labels: &["slider"],
        filename: "akar-slider.png",
        is_website_card: true,
        is_regression: false,
    },
    CaptureEntry {
        family: "stat",
        component: "stat",
        variant: None,
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-stat.png",
        is_website_card: true,
        is_regression: false,
    },
    CaptureEntry {
        family: "steps",
        component: "steps",
        variant: None,
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-steps.png",
        is_website_card: true,
        is_regression: false,
    },
    CaptureEntry {
        family: "switch",
        component: "switch",
        variant: None,
        state: "default",
        script: None,
        labels: &["switch"],
        filename: "akar-switch.png",
        is_website_card: true,
        is_regression: false,
    },
    CaptureEntry {
        family: "tabs",
        component: "tab_bar",
        variant: None,
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-tabs.png",
        is_website_card: true,
        is_regression: false,
    },
    CaptureEntry {
        family: "text_input",
        component: "text_input",
        variant: None,
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-text-input.png",
        is_website_card: true,
        is_regression: false,
    },
    CaptureEntry {
        family: "textarea",
        component: "textarea",
        variant: None,
        state: "default",
        script: None,
        labels: &["textarea"],
        filename: "akar-textarea.png",
        is_website_card: true,
        is_regression: false,
    },
    CaptureEntry {
        family: "toast",
        component: "toasts",
        variant: None,
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-toast.png",
        is_website_card: true,
        is_regression: false,
    },
    CaptureEntry {
        family: "tooltip",
        component: "tooltip",
        variant: None,
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-tooltip.png",
        is_website_card: true,
        is_regression: false,
    },
    // --- 36 registered single variants ---
    // Button variants
    CaptureEntry {
        family: "button",
        component: "button",
        variant: Some("solid"),
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-button-solid.png",
        is_website_card: false,
        is_regression: false,
    },
    CaptureEntry {
        family: "button",
        component: "button",
        variant: Some("outline"),
        state: "default",
        script: None,
        labels: &["button_outline"],
        filename: "akar-button-outline.png",
        is_website_card: false,
        is_regression: false,
    },
    CaptureEntry {
        family: "button",
        component: "button",
        variant: Some("ghost"),
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-button-ghost.png",
        is_website_card: false,
        is_regression: false,
    },
    // Badge variants
    CaptureEntry {
        family: "badge",
        component: "badge",
        variant: Some("default"),
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-badge-default.png",
        is_website_card: false,
        is_regression: false,
    },
    CaptureEntry {
        family: "badge",
        component: "badge",
        variant: Some("primary"),
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-badge-primary.png",
        is_website_card: false,
        is_regression: false,
    },
    CaptureEntry {
        family: "badge",
        component: "badge",
        variant: Some("success"),
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-badge-success.png",
        is_website_card: false,
        is_regression: false,
    },
    CaptureEntry {
        family: "badge",
        component: "badge",
        variant: Some("warning"),
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-badge-warning.png",
        is_website_card: false,
        is_regression: false,
    },
    CaptureEntry {
        family: "badge",
        component: "badge",
        variant: Some("error"),
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-badge-error.png",
        is_website_card: false,
        is_regression: false,
    },
    CaptureEntry {
        family: "badge",
        component: "badge",
        variant: Some("info"),
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-badge-info.png",
        is_website_card: false,
        is_regression: false,
    },
    // Alert variants
    CaptureEntry {
        family: "alert",
        component: "alert",
        variant: Some("info"),
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-alert-info.png",
        is_website_card: false,
        is_regression: false,
    },
    CaptureEntry {
        family: "alert",
        component: "alert",
        variant: Some("success"),
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-alert-success.png",
        is_website_card: false,
        is_regression: false,
    },
    CaptureEntry {
        family: "alert",
        component: "alert",
        variant: Some("warning"),
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-alert-warning.png",
        is_website_card: false,
        is_regression: false,
    },
    CaptureEntry {
        family: "alert",
        component: "alert",
        variant: Some("error"),
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-alert-error.png",
        is_website_card: false,
        is_regression: false,
    },
    // Toast variants
    CaptureEntry {
        family: "toast",
        component: "toasts",
        variant: Some("info"),
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-toast-info.png",
        is_website_card: false,
        is_regression: false,
    },
    CaptureEntry {
        family: "toast",
        component: "toasts",
        variant: Some("success"),
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-toast-success.png",
        is_website_card: false,
        is_regression: false,
    },
    CaptureEntry {
        family: "toast",
        component: "toasts",
        variant: Some("warning"),
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-toast-warning.png",
        is_website_card: false,
        is_regression: false,
    },
    CaptureEntry {
        family: "toast",
        component: "toasts",
        variant: Some("error"),
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-toast-error.png",
        is_website_card: false,
        is_regression: false,
    },
    // Tab variants
    CaptureEntry {
        family: "tabs",
        component: "tab_bar",
        variant: Some("boxed"),
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-tabs-boxed.png",
        is_website_card: false,
        is_regression: false,
    },
    CaptureEntry {
        family: "tabs",
        component: "tab_bar",
        variant: Some("lifted"),
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-tabs-lifted.png",
        is_website_card: false,
        is_regression: false,
    },
    CaptureEntry {
        family: "tabs",
        component: "tab_bar",
        variant: Some("pills"),
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-tabs-pills.png",
        is_website_card: false,
        is_regression: false,
    },
    CaptureEntry {
        family: "tabs",
        component: "tab_bar",
        variant: Some("underline"),
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-tabs-underline.png",
        is_website_card: false,
        is_regression: false,
    },
    // Skeleton variants
    CaptureEntry {
        family: "skeleton",
        component: "skeleton",
        variant: Some("text"),
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-skeleton-text.png",
        is_website_card: false,
        is_regression: false,
    },
    CaptureEntry {
        family: "skeleton",
        component: "skeleton",
        variant: Some("card"),
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-skeleton-card.png",
        is_website_card: false,
        is_regression: false,
    },
    CaptureEntry {
        family: "skeleton",
        component: "skeleton",
        variant: Some("circle"),
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-skeleton-circle.png",
        is_website_card: false,
        is_regression: false,
    },
    // Heading variants
    CaptureEntry {
        family: "heading",
        component: "heading",
        variant: Some("h1"),
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-heading-h1.png",
        is_website_card: false,
        is_regression: false,
    },
    CaptureEntry {
        family: "heading",
        component: "heading",
        variant: Some("h2"),
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-heading-h2.png",
        is_website_card: false,
        is_regression: false,
    },
    CaptureEntry {
        family: "heading",
        component: "heading",
        variant: Some("h3"),
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-heading-h3.png",
        is_website_card: false,
        is_regression: false,
    },
    CaptureEntry {
        family: "heading",
        component: "heading",
        variant: Some("h4"),
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-heading-h4.png",
        is_website_card: false,
        is_regression: false,
    },
    // Drawer variants
    CaptureEntry {
        family: "drawer",
        component: "drawer",
        variant: Some("left"),
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-drawer-left.png",
        is_website_card: false,
        is_regression: true,
    },
    CaptureEntry {
        family: "drawer",
        component: "drawer",
        variant: Some("right"),
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-drawer-right.png",
        is_website_card: false,
        is_regression: false,
    },
    // Tooltip variants
    CaptureEntry {
        family: "tooltip",
        component: "tooltip",
        variant: Some("top"),
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-tooltip-top.png",
        is_website_card: false,
        is_regression: false,
    },
    CaptureEntry {
        family: "tooltip",
        component: "tooltip",
        variant: Some("bottom"),
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-tooltip-bottom.png",
        is_website_card: false,
        is_regression: false,
    },
    CaptureEntry {
        family: "tooltip",
        component: "tooltip",
        variant: Some("left"),
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-tooltip-left.png",
        is_website_card: false,
        is_regression: false,
    },
    CaptureEntry {
        family: "tooltip",
        component: "tooltip",
        variant: Some("right"),
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-tooltip-right.png",
        is_website_card: false,
        is_regression: false,
    },
    // Text input variants
    CaptureEntry {
        family: "text_input",
        component: "text_input",
        variant: Some("normal"),
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-text-input-normal.png",
        is_website_card: false,
        is_regression: false,
    },
    CaptureEntry {
        family: "text_input",
        component: "text_input",
        variant: Some("masked"),
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-text-input-masked.png",
        is_website_card: false,
        is_regression: false,
    },
    // --- State matrix captures ---
    // Button states
    CaptureEntry {
        family: "button",
        component: "button",
        variant: None,
        state: "outline-hover",
        script: Some("button_outline_hover.txt"),
        labels: &["button_outline"],
        filename: "akar-button-outline-hover.png",
        is_website_card: false,
        is_regression: false,
    },
    CaptureEntry {
        family: "button",
        component: "button",
        variant: None,
        state: "outline-pressed",
        script: Some("button_outline_pressed.txt"),
        labels: &["button_outline"],
        filename: "akar-button-outline-pressed.png",
        is_website_card: false,
        is_regression: false,
    },
    // Alert closable state
    CaptureEntry {
        family: "alert",
        component: "alert",
        variant: Some("info"),
        state: "closable",
        script: None,
        labels: &[],
        filename: "akar-alert-info-closable.png",
        is_website_card: false,
        is_regression: false,
    },
    // Checkbox states
    CaptureEntry {
        family: "checkbox",
        component: "checkbox",
        variant: None,
        state: "checked",
        script: Some("checkbox_checked.txt"),
        labels: &["checkbox"],
        filename: "akar-checkbox-checked.png",
        is_website_card: false,
        is_regression: false,
    },
    CaptureEntry {
        family: "checkbox",
        component: "checkbox",
        variant: None,
        state: "unchecked-hover",
        script: Some("checkbox_hover.txt"),
        labels: &["checkbox"],
        filename: "akar-checkbox-hover.png",
        is_website_card: false,
        is_regression: false,
    },
    CaptureEntry {
        family: "checkbox",
        component: "checkbox",
        variant: None,
        state: "unchecked-pressed",
        script: Some("checkbox_pressed.txt"),
        labels: &["checkbox"],
        filename: "akar-checkbox-pressed.png",
        is_website_card: false,
        is_regression: false,
    },
    // Radio second selected
    CaptureEntry {
        family: "radio",
        component: "radio",
        variant: None,
        state: "second-selected",
        script: None,
        labels: &[],
        filename: "akar-radio-second.png",
        is_website_card: false,
        is_regression: false,
    },
    // Switch states
    CaptureEntry {
        family: "switch",
        component: "switch",
        variant: None,
        state: "on",
        script: Some("switch_on.txt"),
        labels: &["switch"],
        filename: "akar-switch-on.png",
        is_website_card: false,
        is_regression: false,
    },
    CaptureEntry {
        family: "switch",
        component: "switch",
        variant: None,
        state: "off-hover",
        script: Some("switch_hover.txt"),
        labels: &["switch"],
        filename: "akar-switch-hover.png",
        is_website_card: false,
        is_regression: false,
    },
    CaptureEntry {
        family: "switch",
        component: "switch",
        variant: None,
        state: "off-pressed",
        script: Some("switch_pressed.txt"),
        labels: &["switch"],
        filename: "akar-switch-pressed.png",
        is_website_card: false,
        is_regression: false,
    },
    // Slider 80%
    CaptureEntry {
        family: "slider",
        component: "slider",
        variant: None,
        state: "80%",
        script: Some("slider_80.txt"),
        labels: &["slider"],
        filename: "akar-slider-80.png",
        is_website_card: false,
        is_regression: false,
    },
    // Select open
    CaptureEntry {
        family: "select",
        component: "select",
        variant: None,
        state: "open",
        script: Some("select_open.txt"),
        labels: &["select"],
        filename: "akar-select-open.png",
        is_website_card: false,
        is_regression: false,
    },
    // Text input states
    CaptureEntry {
        family: "text_input",
        component: "text_input",
        variant: None,
        state: "normal-empty",
        script: None,
        labels: &[],
        filename: "akar-text-input-empty.png",
        is_website_card: false,
        is_regression: false,
    },
    CaptureEntry {
        family: "text_input",
        component: "text_input",
        variant: None,
        state: "normal-focused",
        script: Some("text_input_focus.txt"),
        labels: &["text_input_normal"],
        filename: "akar-text-input-focused.png",
        is_website_card: false,
        is_regression: false,
    },
    CaptureEntry {
        family: "text_input",
        component: "text_input",
        variant: None,
        state: "masked-focused",
        script: Some("text_input_focus.txt"),
        labels: &["text_input_masked"],
        filename: "akar-text-input-masked-focused.png",
        is_website_card: false,
        is_regression: false,
    },
    // Textarea focused
    CaptureEntry {
        family: "textarea",
        component: "textarea",
        variant: None,
        state: "focused",
        script: Some("textarea_focus.txt"),
        labels: &["textarea"],
        filename: "akar-textarea-focused.png",
        is_website_card: false,
        is_regression: false,
    },
    // Tooltip single-side variants (via script)
    CaptureEntry {
        family: "tooltip",
        component: "tooltip",
        variant: Some("top"),
        state: "visible",
        script: Some("tooltip_top.txt"),
        labels: &["tooltip_trigger"],
        filename: "akar-tooltip-top-visible.png",
        is_website_card: false,
        is_regression: false,
    },
    CaptureEntry {
        family: "tooltip",
        component: "tooltip",
        variant: Some("bottom"),
        state: "visible",
        script: Some("tooltip_bottom.txt"),
        labels: &["tooltip_trigger"],
        filename: "akar-tooltip-bottom-visible.png",
        is_website_card: false,
        is_regression: false,
    },
    CaptureEntry {
        family: "tooltip",
        component: "tooltip",
        variant: Some("left"),
        state: "visible",
        script: Some("tooltip_left.txt"),
        labels: &["tooltip_trigger"],
        filename: "akar-tooltip-left-visible.png",
        is_website_card: false,
        is_regression: false,
    },
    CaptureEntry {
        family: "tooltip",
        component: "tooltip",
        variant: Some("right"),
        state: "visible",
        script: Some("tooltip_right.txt"),
        labels: &["tooltip_trigger"],
        filename: "akar-tooltip-right-visible.png",
        is_website_card: false,
        is_regression: false,
    },
    // Tooltip hidden trigger
    CaptureEntry {
        family: "tooltip",
        component: "tooltip",
        variant: None,
        state: "hidden-trigger",
        script: None,
        labels: &["tooltip_trigger"],
        filename: "akar-tooltip-hidden.png",
        is_website_card: false,
        is_regression: false,
    },
    // Progress 100%
    CaptureEntry {
        family: "progress",
        component: "progress",
        variant: None,
        state: "100%",
        script: None,
        labels: &[],
        filename: "akar-progress-100.png",
        is_website_card: false,
        is_regression: false,
    },
    // Steps step 4-of-4
    CaptureEntry {
        family: "steps",
        component: "steps",
        variant: None,
        state: "step4",
        script: None,
        labels: &[],
        filename: "akar-steps-4of4.png",
        is_website_card: false,
        is_regression: false,
    },
    // Data item states
    CaptureEntry {
        family: "data_item",
        component: "data_item",
        variant: None,
        state: "hovered",
        script: Some("data_item_hover.txt"),
        labels: &["data_item"],
        filename: "akar-data-item-hover.png",
        is_website_card: false,
        is_regression: false,
    },
    CaptureEntry {
        family: "data_item",
        component: "data_item",
        variant: None,
        state: "pressed",
        script: Some("data_item_pressed.txt"),
        labels: &["data_item"],
        filename: "akar-data-item-pressed.png",
        is_website_card: false,
        is_regression: false,
    },
    // Scroll area scrolled
    CaptureEntry {
        family: "scroll_area",
        component: "scroll_area",
        variant: None,
        state: "scrolled",
        script: Some("scroll_area_scrolled.txt"),
        labels: &["scroll_area"],
        filename: "akar-scroll-area-scrolled.png",
        is_website_card: false,
        is_regression: false,
    },
    // --- Retained composite images ---
    CaptureEntry {
        family: "form",
        component: "form",
        variant: None,
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-form.png",
        is_website_card: false,
        is_regression: true,
    },
    CaptureEntry {
        family: "navbar",
        component: "navbar",
        variant: None,
        state: "composite",
        script: None,
        labels: &[],
        filename: "akar-navbar-composite.png",
        is_website_card: false,
        is_regression: true,
    },
    CaptureEntry {
        family: "dropdown",
        component: "dropdown",
        variant: None,
        state: "composite",
        script: None,
        labels: &[],
        filename: "akar-dropdown-composite.png",
        is_website_card: false,
        is_regression: true,
    },
    CaptureEntry {
        family: "stats",
        component: "stats",
        variant: None,
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-stats.png",
        is_website_card: false,
        is_regression: true,
    },
    CaptureEntry {
        family: "list",
        component: "list",
        variant: None,
        state: "default",
        script: None,
        labels: &[],
        filename: "akar-list.png",
        is_website_card: false,
        is_regression: true,
    },
];

#[allow(dead_code)]
pub fn total_count() -> usize {
    MANIFEST.len()
}

#[allow(dead_code)]
pub fn website_card_count() -> usize {
    MANIFEST.iter().filter(|e| e.is_website_card).count()
}

#[allow(dead_code)]
pub fn regression_count() -> usize {
    MANIFEST.iter().filter(|e| e.is_regression).count()
}

#[allow(dead_code)]
pub fn scripted_count() -> usize {
    MANIFEST.iter().filter(|e| e.script.is_some()).count()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn manifest_has_expected_entry_count() {
        assert_eq!(MANIFEST.len(), 100);
    }

    #[test]
    fn every_entry_has_filename() {
        for entry in MANIFEST {
            assert!(
                !entry.filename.is_empty(),
                "family '{}' state '{}' has empty filename",
                entry.family,
                entry.state
            );
            assert!(
                entry.filename.ends_with(".png"),
                "family '{}' filename '{}' does not end with .png",
                entry.family,
                entry.filename
            );
        }
    }

    #[test]
    fn every_entry_has_component() {
        for entry in MANIFEST {
            assert!(
                !entry.component.is_empty(),
                "family '{}' has empty component",
                entry.family
            );
        }
    }

    #[test]
    fn filenames_are_unique() {
        let mut filenames: Vec<&str> = MANIFEST.iter().map(|e| e.filename).collect();
        let len_before = filenames.len();
        filenames.sort();
        filenames.dedup();
        assert_eq!(
            filenames.len(),
            len_before,
            "duplicate filenames found in manifest"
        );
    }

    #[test]
    fn website_card_count_is_33() {
        assert_eq!(website_card_count(), 33);
    }

    #[test]
    fn variant_count_is_36() {
        let variant_count = MANIFEST
            .iter()
            .filter(|e| e.variant.is_some() && e.script.is_none())
            .count();
        assert_eq!(variant_count, 37);
    }

    #[test]
    fn scripted_entries_reference_existing_scripts() {
        for entry in MANIFEST {
            if let Some(script) = entry.script {
                let path = format!("scripts/{script}");
                assert!(
                    std::path::Path::new(&path).exists(),
                    "script '{script}' for '{}'/'{}' not found at {path}",
                    entry.family,
                    entry.state
                );
            }
        }
    }

    #[test]
    fn no_duplicate_family_variant_state() {
        let mut keys: Vec<String> = MANIFEST
            .iter()
            .map(|e| format!("{}:{}:{}", e.family, e.variant.unwrap_or(""), e.state))
            .collect();
        let len_before = keys.len();
        keys.sort();
        keys.dedup();
        assert_eq!(
            keys.len(),
            len_before,
            "duplicate family:variant:state combination found"
        );
    }
}
